### ISSUE TITLE
when 2 or more consumers，Every consumer will consume once.

### ISSUE THREAD

**Issue by sundong1982** [majusko/pulsar-java-spring-boot-starter#94] opened 2021-02-23 09:51 UTC
If I want to execute only once, no matter how many nodes. How to solve it?

**Comment by majusko** [comment] 2021-02-23 10:15
Hey @sundong1982, so you would like every node/pod in the cluster to receive the message? This should work with an `Exclusive` subscription but I'm gonna check if it's implemented this way.

**Comment by sundong1982** [comment] 2021-02-25 05:42
i tried subscriptionType = SubscriptionType.Shared,    but multiple application subscribed to the same topic,still not just once.

**Comment by majusko** [comment] 2021-05-19 20:18
Sorry @sundong1982  but this is intended behaviour by Pulsar documentation https://dattell.com/data-architecture-blog/subscription-types-in-apache-pulsar/

You should use `Exclusive` to cover your use case :) 

Closing this.

**Closed** 2021-05-19 20:35 UTC
Labels: invalid
